version: "3"
services:
  strapi:
    container_name: strapi
    image: strapi/strapi:3.4-node14
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - legajo-network
    volumes:
      - ./:/srv/app
      - /srv/app/node_modules/
    ports:
      - "1338:1338"

  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - strapidata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
    networks:
      - legajo-network
  
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
    networks:
      - legajo-network
  
  reportserver:
    container_name: reportserver
    image: docker.io/bitnami/reportserver:4
    ports:
      - '8080:8080'
      - '443:8443'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REPORTSERVER_DATABASE_HOST=mariadb
      - REPORTSERVER_DATABASE_PORT_NUMBER=3306
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
      - TOMCAT_EXTRA_JAVA_OPTS=--add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED -Djavax.net.ssl.trustStoreType=JKS -Drs.configdir=/opt/bitnami/reportserver/WEB-INF/classes
    networks:
      - legajo-network

networks:
  legajo-network:
    driver: bridge

volumes:
  strapidata:
  mariadb_data:


